-- Sprint 3 Week 1: AI-Powered Analytics System
-- Advanced analytics with professional theme analysis and Aboriginal advisor oversight

-- AI Theme Analysis table for story content analysis
CREATE TABLE IF NOT EXISTS ai_theme_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id UUID NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  storyteller_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- AI Analysis Results
  professional_themes JSONB DEFAULT '[]'::jsonb, -- Extracted professional themes with confidence scores
  skill_categories JSONB DEFAULT '[]'::jsonb, -- Professional skills identified in the story
  industry_relevance JSONB DEFAULT '[]'::jsonb, -- Industry connections and relevance scores
  collaboration_indicators JSONB DEFAULT '[]'::jsonb, -- Signals for partnership potential
  cultural_competency_markers JSONB DEFAULT '[]'::jsonb, -- Cultural sensitivity indicators
  
  -- AI Confidence and Quality Metrics
  analysis_confidence DECIMAL(3,2) DEFAULT 0.0, -- Overall confidence in analysis (0.0-1.0)
  theme_clarity_score DECIMAL(3,2) DEFAULT 0.0, -- How clearly themes are expressed
  professional_relevance_score DECIMAL(3,2) DEFAULT 0.0, -- Professional applicability score
  
  -- Cultural Review Status
  cultural_review_status TEXT DEFAULT 'pending' CHECK (cultural_review_status IN ('pending', 'reviewed', 'flagged', 'approved')),
  cultural_review_notes TEXT,
  aboriginal_advisor_feedback JSONB DEFAULT '{}'::jsonb,
  
  -- AI Model Information
  ai_model_version TEXT NOT NULL,
  analysis_date TIMESTAMPTZ DEFAULT NOW(),
  last_cultural_review TIMESTAMPTZ,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Professional Insights generated by AI analysis
CREATE TABLE IF NOT EXISTS ai_professional_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  story_id UUID NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  storyteller_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  theme_analysis_id UUID REFERENCES ai_theme_analysis(id) ON DELETE CASCADE,
  
  -- Insight Content
  insight_type TEXT CHECK (insight_type IN ('methodology', 'approach', 'outcome', 'lesson', 'principle')) NOT NULL,
  insight_title TEXT NOT NULL,
  insight_content TEXT NOT NULL,
  professional_applications TEXT[], -- Where this insight applies professionally
  
  -- AI Analysis
  relevance_score DECIMAL(3,2) DEFAULT 0.0, -- How relevant to professional context
  uniqueness_score DECIMAL(3,2) DEFAULT 0.0, -- How unique/differentiating this insight is
  collaboration_potential DECIMAL(3,2) DEFAULT 0.0, -- Partnership opportunity indicator
  
  -- Cultural Validation
  cultural_appropriateness_score DECIMAL(3,2) DEFAULT 0.0,
  requires_cultural_review BOOLEAN DEFAULT false,
  cultural_validation_status TEXT DEFAULT 'approved' CHECK (cultural_validation_status IN ('pending', 'approved', 'rejected', 'requires_modification')),
  
  -- Engagement Tracking
  reader_saves INTEGER DEFAULT 0,
  professional_inquiries_generated INTEGER DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enhanced storyteller intelligence dashboard data
CREATE TABLE IF NOT EXISTS storyteller_ai_intelligence (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  storyteller_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Professional Profile AI Analysis
  core_expertise_areas JSONB DEFAULT '[]'::jsonb, -- Primary areas of professional strength
  collaboration_style JSONB DEFAULT '{}'::jsonb, -- How they work with others
  cultural_competency_level TEXT CHECK (cultural_competency_level IN ('developing', 'intermediate', 'advanced', 'expert')),
  innovation_indicators JSONB DEFAULT '[]'::jsonb, -- Markers of innovative thinking
  
  -- Professional Networking Intelligence
  ideal_collaboration_profiles JSONB DEFAULT '[]'::jsonb, -- Types of partners who would work well
  professional_growth_trajectory JSONB DEFAULT '{}'::jsonb, -- Career development patterns
  community_impact_potential DECIMAL(3,2) DEFAULT 0.0, -- Potential for community benefit
  
  -- Storytelling Quality Metrics
  narrative_authenticity_score DECIMAL(3,2) DEFAULT 0.0,
  professional_credibility_score DECIMAL(3,2) DEFAULT 0.0,
  story_engagement_quality DECIMAL(3,2) DEFAULT 0.0,
  
  -- Cultural Integration Assessment
  aboriginal_protocol_adherence DECIMAL(3,2) DEFAULT 0.0,
  community_centered_approach DECIMAL(3,2) DEFAULT 0.0,
  cultural_sensitivity_indicators JSONB DEFAULT '[]'::jsonb,
  
  -- AI Processing Metadata
  last_analysis_date TIMESTAMPTZ DEFAULT NOW(),
  analysis_completeness DECIMAL(3,2) DEFAULT 0.0, -- How complete the analysis is
  requires_human_review BOOLEAN DEFAULT false,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Aboriginal Advisory Council integration for cultural oversight
CREATE TABLE IF NOT EXISTS aboriginal_advisory_reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Review Subject
  review_type TEXT CHECK (review_type IN ('story_content', 'ai_analysis', 'theme_categorization', 'cultural_representation')) NOT NULL,
  subject_id UUID NOT NULL, -- Can reference story_id, theme_analysis_id, etc.
  storyteller_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Advisor Information
  advisor_id UUID REFERENCES profiles(id), -- If advisor has profile on platform
  advisor_name TEXT NOT NULL,
  advisor_credentials TEXT,
  community_affiliation TEXT,
  
  -- Review Content
  review_status TEXT DEFAULT 'pending' CHECK (review_status IN ('pending', 'approved', 'requires_changes', 'rejected')) NOT NULL,
  cultural_assessment JSONB DEFAULT '{}'::jsonb, -- Structured cultural review
  recommended_changes TEXT,
  cultural_protocol_notes TEXT,
  
  -- Review Process
  priority_level TEXT DEFAULT 'standard' CHECK (priority_level IN ('low', 'standard', 'high', 'urgent')),
  review_deadline TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  
  -- Follow-up Tracking
  changes_implemented BOOLEAN DEFAULT false,
  follow_up_required BOOLEAN DEFAULT false,
  follow_up_notes TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- AI-powered recommendation engine data
CREATE TABLE IF NOT EXISTS ai_story_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Recommendation Context
  for_reader_id UUID REFERENCES profiles(id), -- NULL for anonymous/general recommendations
  recommended_story_id UUID NOT NULL REFERENCES stories(id) ON DELETE CASCADE,
  recommendation_type TEXT CHECK (recommendation_type IN ('similar_themes', 'complementary_expertise', 'collaboration_potential', 'cultural_resonance')) NOT NULL,
  
  -- AI Reasoning
  relevance_score DECIMAL(3,2) DEFAULT 0.0,
  confidence_score DECIMAL(3,2) DEFAULT 0.0,
  reasoning_factors JSONB DEFAULT '[]'::jsonb, -- Why this was recommended
  theme_match_details JSONB DEFAULT '{}'::jsonb,
  
  -- Recommendation Performance
  presented_to_reader BOOLEAN DEFAULT false,
  reader_clicked BOOLEAN DEFAULT false,
  reader_engaged BOOLEAN DEFAULT false, -- Read significant portion
  reader_saved BOOLEAN DEFAULT false,
  
  -- Cultural Appropriateness
  cultural_sensitivity_verified BOOLEAN DEFAULT false,
  cultural_match_score DECIMAL(3,2) DEFAULT 0.0,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '30 days')
);

-- Enhanced analytics aggregation with AI insights
CREATE TABLE IF NOT EXISTS ai_enhanced_analytics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  storyteller_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Time Period
  period_type TEXT CHECK (period_type IN ('daily', 'weekly', 'monthly', 'quarterly')) NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  
  -- AI-Enhanced Engagement Metrics
  professional_theme_resonance JSONB DEFAULT '{}'::jsonb, -- Which themes are connecting with readers
  collaboration_inquiry_patterns JSONB DEFAULT '{}'::jsonb, -- Types of professional interest generated
  cultural_competency_feedback JSONB DEFAULT '{}'::jsonb, -- Cultural sensitivity tracking
  
  -- Professional Development Insights
  expertise_recognition_growth DECIMAL(5,2) DEFAULT 0.0, -- Growing recognition in specific areas
  networking_effectiveness DECIMAL(3,2) DEFAULT 0.0, -- How well stories facilitate connections
  community_impact_indicators JSONB DEFAULT '[]'::jsonb,
  
  -- AI Recommendations Performance
  recommendation_click_rate DECIMAL(3,2) DEFAULT 0.0,
  cross_story_engagement DECIMAL(3,2) DEFAULT 0.0,
  reader_journey_completion DECIMAL(3,2) DEFAULT 0.0,
  
  -- Cultural Integration Metrics
  aboriginal_protocol_alignment DECIMAL(3,2) DEFAULT 0.0,
  community_value_generation DECIMAL(10,2) DEFAULT 0.0, -- Economic/social value created
  cultural_authenticity_feedback DECIMAL(3,2) DEFAULT 0.0,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for AI analytics performance
CREATE INDEX IF NOT EXISTS idx_ai_theme_analysis_story ON ai_theme_analysis(story_id);
CREATE INDEX IF NOT EXISTS idx_ai_theme_analysis_storyteller ON ai_theme_analysis(storyteller_id);
CREATE INDEX IF NOT EXISTS idx_ai_theme_analysis_cultural_status ON ai_theme_analysis(cultural_review_status);
CREATE INDEX IF NOT EXISTS idx_ai_professional_insights_story ON ai_professional_insights(story_id);
CREATE INDEX IF NOT EXISTS idx_ai_professional_insights_type ON ai_professional_insights(insight_type);
CREATE INDEX IF NOT EXISTS idx_storyteller_ai_intelligence_storyteller ON storyteller_ai_intelligence(storyteller_id);
CREATE INDEX IF NOT EXISTS idx_aboriginal_advisory_reviews_subject ON aboriginal_advisory_reviews(subject_id, review_type);
CREATE INDEX IF NOT EXISTS idx_aboriginal_advisory_reviews_status ON aboriginal_advisory_reviews(review_status);
CREATE INDEX IF NOT EXISTS idx_ai_story_recommendations_reader ON ai_story_recommendations(for_reader_id);
CREATE INDEX IF NOT EXISTS idx_ai_story_recommendations_story ON ai_story_recommendations(recommended_story_id);
CREATE INDEX IF NOT EXISTS idx_ai_enhanced_analytics_storyteller ON ai_enhanced_analytics(storyteller_id, period_type);

-- Row Level Security
ALTER TABLE ai_theme_analysis ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_professional_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE storyteller_ai_intelligence ENABLE ROW LEVEL SECURITY;
ALTER TABLE aboriginal_advisory_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_story_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_enhanced_analytics ENABLE ROW LEVEL SECURITY;

-- RLS Policies for AI Analytics

-- Storytellers can view their own AI analysis
CREATE POLICY "storytellers_view_ai_analysis" ON ai_theme_analysis
  FOR SELECT USING (storyteller_id = auth.uid());

CREATE POLICY "storytellers_view_ai_insights" ON ai_professional_insights
  FOR SELECT USING (storyteller_id = auth.uid());

CREATE POLICY "storytellers_view_ai_intelligence" ON storyteller_ai_intelligence
  FOR SELECT USING (storyteller_id = auth.uid());

-- Aboriginal advisors can view and manage cultural reviews
CREATE POLICY "advisors_manage_cultural_reviews" ON aboriginal_advisory_reviews
  FOR ALL USING (
    auth.uid() IN (
      SELECT id FROM profiles WHERE role = 'aboriginal_advisor' OR role = 'admin'
    )
  );

-- Storytellers can view their cultural reviews
CREATE POLICY "storytellers_view_cultural_reviews" ON aboriginal_advisory_reviews
  FOR SELECT USING (storyteller_id = auth.uid());

-- AI recommendations viewable by relevant readers
CREATE POLICY "readers_view_recommendations" ON ai_story_recommendations
  FOR SELECT USING (
    for_reader_id = auth.uid() OR for_reader_id IS NULL
  );

-- Enhanced analytics viewable by storytellers
CREATE POLICY "storytellers_view_enhanced_analytics" ON ai_enhanced_analytics
  FOR SELECT USING (storyteller_id = auth.uid());

-- Functions for AI analytics processing

-- Function to trigger AI theme analysis for new stories
CREATE OR REPLACE FUNCTION trigger_ai_theme_analysis()
RETURNS trigger AS $$
BEGIN
  -- Insert placeholder AI analysis record for processing
  INSERT INTO ai_theme_analysis (
    story_id,
    storyteller_id,
    ai_model_version,
    analysis_confidence
  ) VALUES (
    NEW.id,
    NEW.storyteller_id,
    'gpt-4-theme-analyzer-v1',
    0.0 -- Will be updated by AI processing
  );
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger AI analysis when stories are published
CREATE TRIGGER stories_trigger_ai_analysis
  AFTER INSERT OR UPDATE OF content_status ON stories
  FOR EACH ROW
  WHEN (NEW.content_status = 'published')
  EXECUTE FUNCTION trigger_ai_theme_analysis();

-- Function to update storyteller AI intelligence
CREATE OR REPLACE FUNCTION update_storyteller_ai_intelligence(storyteller_uuid UUID)
RETURNS void AS $$
BEGIN
  INSERT INTO storyteller_ai_intelligence (
    storyteller_id,
    last_analysis_date,
    analysis_completeness
  ) VALUES (
    storyteller_uuid,
    NOW(),
    0.0 -- Will be updated by AI processing
  )
  ON CONFLICT (storyteller_id) 
  DO UPDATE SET
    last_analysis_date = NOW(),
    requires_human_review = false;
END;
$$ LANGUAGE plpgsql;

-- Function to process AI recommendations
CREATE OR REPLACE FUNCTION generate_ai_recommendations(reader_uuid UUID DEFAULT NULL)
RETURNS TABLE (
  story_id UUID,
  story_title TEXT,
  relevance_score DECIMAL,
  recommendation_reason TEXT
) AS $$
BEGIN
  -- Simplified recommendation logic - in production this would use ML models
  RETURN QUERY
  SELECT 
    s.id,
    s.title,
    CAST(0.8 AS DECIMAL) as relevance_score,
    'Similar professional themes and cultural competency' as recommendation_reason
  FROM stories s
  WHERE s.content_status = 'published'
  AND (reader_uuid IS NULL OR s.storyteller_id != reader_uuid)
  ORDER BY s.view_count DESC, s.created_at DESC
  LIMIT 10;
END;
$$ LANGUAGE plpgsql;

COMMENT ON TABLE ai_theme_analysis IS 'AI-powered analysis of story themes with Aboriginal advisor oversight';
COMMENT ON TABLE ai_professional_insights IS 'Professional insights extracted from stories by AI analysis';
COMMENT ON TABLE storyteller_ai_intelligence IS 'Comprehensive AI-generated professional intelligence for storytellers';
COMMENT ON TABLE aboriginal_advisory_reviews IS 'Cultural review and oversight by Aboriginal Advisory Council';
COMMENT ON TABLE ai_story_recommendations IS 'AI-powered story recommendations with cultural sensitivity';
COMMENT ON TABLE ai_enhanced_analytics IS 'Advanced analytics enhanced with AI insights and cultural metrics';